apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  serviceAccountName: default
  params:
    - name: context-dir
      value: "."
    - name: dockerfile
      value: "./Dockerfile"
    - name: docker-image
      value: "https://hub.docker.com/r/jarvis99/railsapp:latest"
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
          - name: url
            value: "https://github.com/V-vk-404/DevOps-Assesment.git"
  secrets:
    - name: regcred
