apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ruby-rails
  name: rails-ing
spec:
  rules:
  - host: sample-rails.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rails-app-service
          servicePort: 3000
